file_paths:
    working_dir: "/global/homes/r/rmastand/dimuonAD/"
    data_storage_dir: "/global/cfs/cdirs/m3246/rmastand/dimuonAD/"

analysis_keywords:
    name: "upsilon_iso_12_03"
    particle: upsilon
    analysis_cuts: 
        lower:
            mu0_iso04: 0.55
            mu1_iso04: 0.55
            mu0_pt: 17
            mu1_pt: 8
            HLT_TrkMu15_DoubleTrkMu5NoFiltersNoVtx: 1
        upper: 
    dataset_id: lowmass
    

window_definitions:
    upsilon: 
        SB_left: 5
        SR_left: 9
        SR_right: 10.6
        SB_right: 16
    eta:
        SB_left: 0.3
        SR_left: 0.525
        SR_right: 0.569
        SB_right: 0.72

bdt_hyperparameters:
    n_estimators: 300 # number of boosting stages
    max_depth: 3 # max depth of individual regression estimators; related to complexity
    learning_rate: 0.1  # stop training BDT is validation loss doesn't improve after this many rounds
    subsample: 0.7   # fraction of samples to be used for fitting the individual base learners
    early_stopping_rounds: 10


feature_sets:
    single_0:
        - mu0_pt
        - mu1_pt
        - mu0_eta
        - mu1_eta
    single_1: 
        - mu0_iso04
        - mu1_iso04
    single_2: 
        - mu0_pt
        - mu1_pt
    single_3: 
        - mu0_ip3d
        - mu1_ip3d
    double_0: 
        - dimu_pt
        - dimu_eta
        - mumu_deltaR
        - mumu_deltapT
    double_1: 
        - dimu_pt
        - dimu_eta
    double_2: 
        - mumu_deltaR
        - mumu_deltapT
    mix_0: 
        - dimu_pt
        - mu0_iso04
        - mu1_iso04       
    mix_2: 
        - dimu_pt
        - mu0_ip3d
        - mu1_ip3d


