file_paths:
    working_dir: "/global/homes/r/rmastand/dimuonAD/"
    data_storage_dir: "/global/cfs/cdirs/m3246/rmastand/dimuonAD/"

window_definitions:
    upsilon: 
        SB_left: 7.8
        SR_left: 9
        SR_right: 10.6
        SB_right: 15



feature_sets:
    single_0:
        - mu0_pt
        - mu1_pt
        - mu0_eta
        - mu1_eta
    single_1: 
        - mu0_iso04
        - mu1_iso04
    single_2: 
        - mu0_pt
        - mu1_pt
    single_3: 
        - mu0_ip3d
        - mu1_ip3d
        - mu0_jetiso
        - mu1_jetiso
    single_4: 
        - mu0_ip3d
        - mu1_ip3d
    single_5: 
        - mu0_jetiso
        - mu1_jetiso
    double_0: 
        - dimu_pt
        - dimu_eta
        - mumu_deltaR
        - mumu_deltapT
    double_1: 
        - dimu_pt
        - dimu_eta
    double_2: 
        - mumu_deltaR
        - mumu_deltapT
    mix_0: 
        - dimu_pt
        - mu0_iso04
        - mu1_iso04     
    mix_2: 
        - dimu_pt
        - mu0_ip3d
        - mu1_ip3d


eta:
    SB_left: 0.3
    SR_left: 0.525
    SR_right: 0.569
    SB_right: 0.72

