num_layers: 4
num_hidden_features: 4
num_blocks: 4
early_stop_patience: 20
spline_type: "PRQ"

hyperparameters_dict:
    n_epochs: 200
    batch_size: 128
    lr: 0.0001
    weight_decay: 0.00

flow_training_id: "cathode_insp_5"